### ISSUE TITLE
[Fix]: One-Click Installation Options underlying links redirects to 'Page Not Found'

### ISSUE THREAD

**Issue by scripnichenko** [stereum-dev/ethereum-node-web-docs#42]
### Describe the issue

![image](https://github.com/stereum-dev/ethereum-node-web-docs/assets/4344096/d172424d-6ad2-4fce-b0c4-1b0de832e28d)

### Location of the issue

https://stereum-dev.github.io/ethereum-node-web-docs/docs/guides/installation/installation-options/one-click-installation#one-click-installation-options

### Suggested Correction

Update underlying links. 

Example for [Ethereum Solo Staking Guide]
🤧  **Actual link** 
https://stereum-dev.github.io/ethereum-node-web-docs/docs/guides/installation/installation-options/02-installation/01-use-case-guides/01-staking/00-ethereum/01-ethereum-solo-staking.md
✅  **Expected link**
https://stereum-dev.github.io/ethereum-node-web-docs/docs/guides/installation/use-case-guides/staking/ethereum/ethereum-solo-staking

**Comment by daGscheid** [comment]
Thank you for the report. Will take care of it right now 🙏
